---
.travis.yml:
  secure_global_env:
    # PUBLISHER_PASSWORD
    - "YcTQBZeD2N5EjRDpY1E3IJLMIcrzNSiHYbMUvpZD/z1DLVCrURIfxzQ1GXQ9\nMIGCESKSGsZUOhstPpEsCgqec5bNjmJigAQbxplzid6Pa+KGjpszFJvb/rbo\nEfvwfOwHqkFgcl6NJVZofM3A9YoFI/ndSU7OVUFJA1qNpgM4s7A="
